spring:
    datasource:
      url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
      username: ab
      password: 5241533011
      schema: database/import.sql
      sql-script-encoding: utf-8
      driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      database: mysql
      show-sql: true
      hibernate:
          ddl-auto: update
          naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
      servlet:
        multipart:
          enabled: true
          max-file-size: 50mb
          max-request-size: 50mb
    thymeleaf:
       cache: false
       mode: HTML
       prefix: classpath:/templates/
    application:
      name: shiro

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://peer2:8761/eureka/,http://peer1:8761/eureka/
      #defaultZone: http://localhost:8761/eureka/
file:
  uploadDir: /classdesign/
